### PR TITLE
Updated contributors layout and added Taru to the student contributors

### PR DESCRIPTION
**Pull request by AdamMiltonBarker**
## Description

- Added two categories to Contributors section in page footers, Team & Students/Research Interns
- Added Taru Jain to Students/Research Intern contributors

## Linked Issue
https://github.com/AMLResearchProject/AML-ALL-Classifiers/issues/66

## Checklist (Delete Yes/No as appropriate)
_Have you ensured the linked issue above is correct?_ Yes

_Have you ensured your code and/or documentation follows the formatting style of this repository?_ Yes

_Have you included the project branding (logos/banners)?_ Yes

_Have you added documentation and/or updated existed documentation with related information?_ Yes

_Have you completed all of the required changes to resolve the issue?_ Yes

_Have you completed all of the above?_ Yes

### CODE REVIEW

**Comment by holeung** [comment]
okay.

**Comment by holeung** [comment]
okay

**Review by holeung — APPROVED** [review]
okay

**Comment by amita-kapoor** [comment]
Perfect

**Pull request merged**
